package aula05;

public class Exe00_IntroducaoObjeto {

	public static void main(String[] args) {

		/*
		 * PARADIGMA: PALAVRA BONITA QUE QUER DIZER 'MODELO'
		 * 
		 * PARADIGMA ORIENTADO A OBJETOS: CONJUNTO DE TÉCNICAS QUE PROCURA REPRESENTAR PARTES DO MUNDO REAL EM PROGRAMAS DE CONPUTADOR.
		 * 
		 * OS "REPRESENTANTES DO MUNDO REAL" SÃO OS 'OBJETOS' E AS "PARTES DO MUNDO REAL" SÃO CHAMADAS 'DOMÍNIO'. 
		 * 
		 * *EXEMPLO DE DOMÍNIO:
		 * 
		 * CONSIDERE UM SISTEMA ACADÊMICO. O DOMÍNIO DO PROBLEMA É O "AMBIENTE DA UNIVERSIDADE", E OS "OBJETOS" 
		 * REPRESENTADOS NO SISTEMA SERÃO 'ALUNOS', 'PROFESSORES', 'DISCIPLINAS', 'CURSOS', 'AVALIAÇÕES', ETC.
		 * 
		 * *EXEMPLO DE OBJETOS:
		 * 
		 * CONSIDERE AGORA UM SISTEMA DE VENDAS ONLINE. OS OBJETOS MODELADOS SERÃO OS 'CLIENTES', 'OS PRODUTOS', 
		 * 'O CARRINHO DE COMPRAS', 'O CARTÃO DE CRÉDITO', 'O ESTOQUE', ETC.
		 * 
		 * ABSTRAÇÃO: CAPACIDADE DE IGNORAR DETALHES DE PARTES PARA FOCALIZAR A ATENÇÃO EM UM NÍVEL MAIS ELEVADO DE UM PROBLEMA.
		 * 
		 * MODULARIZAÇÃO: PROCESSO DE DIVIDIR UM TODo EM PARTES BEM DEFINIDAS, QUE PODEM SER CONSTRUÍDAS E EXAMINADAS
		 * SEPARADAMENTE E QUE INTERAGEM DE MANEIRAS BEM DEFINIDAS.
		 * 
		 * ORIENTAÇÃO A OBJETOS: FORMA DE MODELAR O MUNDO REAL EM UM SISTEMA.
		 * 
		 * OBJETO:ELEMENTO DO MUNDO REAL REPRESENTADO EM UM SISTEMA.
		 *
		 * CLASSE: DEFINIÇÃO DOS OBJETOS EM TERMOS DE ATRIBUTOS E MÉTODOS.
		 * 
		 * ATRIBUTO: EXPRESSA CARACTERÍSTICAS DE UM OBJETO.
		 * 
		 * MÉTODO: DEFINE AS AÇÕES DE UM OBJETO.
		 * 
		 * CHAMADA DE MÉTODO: OS OBJETOS SE COMUNICAM CHAMANDO MÉTODOS UNS DOS OUTROS.
		 * 
		 * ASSINATURA: É O CABEÇALHO DE UM MÉTODO QUE FORNECE INFORMAÇÕES COMO CHAMÁ-LO.
		 * 
		 * RETORNO: OS MÉTODOS RETORNAM ALGUM TIPO DE DADO OU VOID SE NÃO RETORNAM NADA.
		 * 
		 * TIPO DE DADO: INDICA O CONJUNTO DE VALORES QUE UM ATRIBUTO OU PARÂMETRO PODEM ASSUMIR OU QUE UM MÉTODO PODE RETORNAR.
		 * 
		 * TIPO PRIMITIVO: SÃO TIPOS BÁSICOS QUE NÃO TEM MÉTODOS, CRIADOS A PARTIR DOS TIPOS PRIMITIVOS E DE OUTROS TIPOS OBJETO.
		 * 
		 * ESTADO: CONJUNTO DE VALORES DOS ATRIBUTOS DE UM OBJETO EM UM DETERMINADO MOMENTO.
		 * 
		 * MÉTODO MODIFICADOR: ALTERA O VALOR DE UM ATRIBUTO, MUDANDO O ESTADO DO OBJETO.
		 * 
		 * MÉTODO DE ACESSO: RETORNA O VALOR DE UM ATRIBUTO.
		 * 
		 * CONSTRUTOR: INSTÂNCIA UM OBJETO, GERALMENTE ATRINUINDO VALORES PARA SEUS ATRIBUTOS.
		 * 
		 * PARÂMETRO: VALORES PASSADOS PARA OS MÉTODOS COMO INFORMAÇÕES ADICIONAIS.
		 * 
		 */

	}

}












